config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  resources :users
  resources :issues
  resources :issues do
    resources :comments
  end
  get '/users/current_user' => "users#the_current_user", as: :current_user
  get  'static_pages/home'
  get  'static_pages/help'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  


  #Routes for vote
  post '/issues/:id/vote' => "issues#vote", as: :vot
  post '/issues/:id/watcher/:index' => "issues#watcher", as: :watch
  put '/issues/:id/status' => "issues#update_status", as: :update_status

  put '/issues' => 'application#set_current_user', as: :log



 

end

app/models/issue.rb
class Issue < ApplicationRecord
	#belongs_to :user
    belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id, optional: true
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :watchers, dependent: :destroy
    validates :Title, :Type, :Priority, :Status, presence: true
 
    def self.status
        ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
    end
    def self.type
        ["Bug", "Enhancement", "Proposal", "Task"]
    end
    def self.priority
        ["Trivial", "Minor", "Major", "Critical", "Blocker"]
    end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_current_user
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order(sort_column + ' ' + sort_direction)
    @issues = @issues.where(Type: params[:Type]) if params[:Type]
    @issues = @issues.where(Priority: params[:Priority]) if params[:Priority]
    @issues = @issues.where(Status: params[:Status]) if params[:Status]


    respond_to do |format|
      
      if params.has_key?(:assignee_id)
        if User.exists?(id: params[:assignee_id])
          @issues = @issues.where(assignee_id: params[:assignee_id])
        else
          format.json {render json: {"error":"User with id="+params[:assignee_id]+" does not exist"}, status: :unprocessable_entity}
        end
      end
      
      if params.has_key?(:type)
        @issues = @issues.where(Type: params[:type])
      end
      
      if params.has_key?(:priority)
        @issues = @issues.where(Priority: params[:priority])
      end
      
      if params.has_key?(:status)
        if params[:status] == "New&Open"
          @issues = @issues.where(Status: ["Open","New"])
        else
        @issues = @issues.where(Status: params[:status])
        end
      end

      if params.has_key?(:watcher)
        if User.exists?(id: params[:watcher])
          @issues = Issue.joins(:watchers).where(watchers:{user_id: params[:watcher]})
        else
          format.json {render json: {"error":"User with id="+params[:watcher]+" does not exist"}, status: :unprocessable_entity}
        end
      end

      format.html
      format.json {render json: @issues, status: :ok, each_serializer: IssueIndexSerializer}
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.user_id = current_user.id
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    respond_to do |format|
      @issue_to_update = Issue.find(params[:id])
      @issue_to_update.update_attribute("Status", params[:status])
      @comment = Comment.new()
      @comment.issue_id = @issue_to_update.id
      @comment.user_id = current_user.id
      @comment.body = " changed status to " + params[:status]
      @comment.save
      format.html { redirect_to @issue_to_update }
      format.json { render json: @issue_to_update, status: :ok }
    end
  end

  # POST /issues/{issue_id}/vote
  def vote
        respond_to do |format|
          @issue_to_vote = Issue.find(params[:id])
          if !Vote.exists?(:issue_id => @issue_to_vote.id, :user_id => current_user.id)
            @vote = Vote.new
            @vote.user_id = current_user.id
            @vote.issue_id = @issue_to_vote.id
            @vote.save
            @issue_to_vote.increment!("Votes")
          else
            @vote = Vote.where(issue_id: params[:id], user_id: current_user.id).take
            @vote.destroy
            @issue_to_vote.decrement!("Votes")
          end
          format.html { redirect_to @issue_to_vote }
          format.json { render json: @issue_to_vote, status: :ok }
        end
    end

  # POST /issues/{issue_id}/watcher
    def watcher
        respond_to do |format|
          @issue_to_watcher = Issue.find(params[:id])
          if !Watcher.exists?(:issue_id => @issue_to_watcher.id, :user_id => current_user.id)
            @watcher = Watcher.new
            @watcher.user_id = current_user.id
            @watcher.issue_id = @issue_to_watcher.id
            @watcher.save
            @issue_to_watcher.increment!("Watchers")
          else
            @watcher = Watcher.where(issue_id: params[:id], user_id: current_user.id).take
            @watcher.destroy
            @issue_to_watcher.decrement!("Watchers")
          end
          if params[:index] != "index"
            format.html { redirect_to @issue_to_watcher }
            format.json { render json: @issue_to_watcher, status: :ok }
          else
            format.html { redirect_to issues_url, notice: 'Watching Issue' }
            format.json { head :no_content }
          end
          
        end
    end

    # POST /issues/{issue_id}/comment
   
  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def sort_column
      Issue.column_names.include?(params[:sort]) ? params[:sort] : ''
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : ''
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:Title, :Description, :Type, :Priority, :Status, :assignee_id, :attachment)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="input-group">
    <%= form.label :Title %>
    <%= form.text_field :Title, id: :issue_Title %>
  </div>

  <div class="input-group">
    <%= form.label :Description %>
    <%= form.text_area :Description, id: :issue_Description %>
  </div>

  <div class="input-group">
    <%= form.label :Type %>
    <%= form.select :Type, options_for_select(Issue.type, issue[:Type]), prompt: true, :class => 'genForm_dropBox' %>
  </div>

  <div class="input-group">
    <%= form.label :Priority %>
    <%= form.select :Priority, options_for_select(Issue.priority, issue[:Priority]), prompt: true, :class => 'genForm_dropBox' %>
  </div>

  <div class="input-group">
    <%= form.label :Status %>
    <%= form.select :Status, options_for_select(Issue.status), :class => 'genForm_dropBox' %>
  </div>
  
  <div class="input-group">
    <%= form.label :Assignee %>
    <%= form.collection_select :assignee_id, User.all, :id, :name, {:include_blank => 'No assigned user'} %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'submit' %>
    <%= link_to 'Cancel', issues_path, :class => 'cancel' %>
  </div>
  
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<!DOCTYPE html>

<div class="header">
  <div class="section-title">
    <h1>Issues</h1>

    <% if current_user %>
      <div class = section-subtitle> The current user is: <%= current_user.name %> </div>
    <%end%>
  </div>
   <% if current_user %>
    <div class = create-issue>
      <button type="button" class="btn btn-light">
        <%= link_to new_issue_path, class: 'create-button' do %>
            <span class="createi-button">Create issue</span>
          <% end %>
      </button>
    </div>
  <%end%>
</div>


<div class="issues">
  <div class="issues-toolbar">
    <div class="filter-container">
      <p class="filter-label">Filters:</p>
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group" role="group" aria-label="Third group">
          <button type="button" class="btn btn-secondary"><a href="/issues">All</a></button>
        </div>
        <div class="btn-group" role="group" aria-label="Third group">
          <button type="button" class="btn btn-secondary"><a><%= link_to "Open", issues_url(status: "New&Open")%></a></button>
        </div>
        <% if current_user %>
          <div class="btn-group" role="group" aria-label="Third group">
            <button type="button" class="btn btn-secondary"><a><%= link_to "My issues", issues_url(assignee: current_user.id)%></a></button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-secondary"><a><%= link_to "Watching", issues_url(watcher: current_user.id)%></a></button>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

  <p id="issues-filter-criteria">
    <% if request.query_parameters[:type] %>
      <b>type:</b> "<%= request.query_parameters[:type] %>"
    <% end %>
    <% if request.query_parameters[:priority] %>
        <b>priority:</b> "<%= request.query_parameters[:priority] %>"
    <% end %>
    <% if request.query_parameters[:status] %>
        <b>status:</b> "<%= request.query_parameters[:status] %>"
    <% end %>
    <% if request.query_parameters[:assignee_id] %>
        <b>assignee:</b> "<%= User.find(request.query_parameters[:assignee_id]).name %>"
    <% end %>
  </p>

  <div class = section-subtitle>Issues (<%= @issues.size %>) </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <%= sortable "id", "Title" %>
        <%= sortable "Type", "T" %>
        <%= sortable "Priority", "P" %>
        <%= sortable "Status", "S" %>
        <%= sortable "Votes", "Votes" %>
        <%= sortable "assignee_id", "Assignee" %>
        <%= sortable "created_at", "Created" %>
        <%= sortable "updated_at", "Updated" %>
      </tr>
    </thead>
    <tbody>
      <% @issues.each do |issue| %>
        <tr><!--@products = Product.status("active").starts_with("Ruby")-->
          <td><%= link_to issue.Title , issue, class:"btn-link" %></td>
          <td><%= link_to issue.Type , issues_url(type: issue.Type), class:"btn-link" %></td>
          <td><%= link_to issue.Priority , issues_url(priority: issue.Priority), class:"btn-link" %></td>
          <td><%= link_to issue.Status , issues_url(status: issue.Status), class:"btn-link" %></td>
          <td><%= issue.Votes %></td>
          <% if !issue.assignee_id.nil? %>
            <td><%= link_to User.find(issue.assignee_id).name, issues_url(assignee_id: issue.assignee_id) , class:"btn-link" %></td>
            <% else %>
            <td></td>
            <% end %>
            <td><%= time_ago_in_words(issue.created_at) + " ago" %></td>
            <td><%= time_ago_in_words(issue.updated_at) + " ago" %></td>
            <td>
            <% if current_user %> 
              <% if !Watcher.exists?(:issue_id => issue.id, :user_id => current_user.id) %>
                <%= link_to 'Watch', watch_url(id: issue.id, index: "index" ), method: :post, class:"watcher" %>
              <%else %>
                <%= link_to 'Unwatch', watch_url(id: issue.id, index: "index"), method: :post, class:"watcher" %>
              <% end %>
            <%end%>
            </td>
            <% if current_user %> 
              <% if current_user.id == issue.user_id %> 
                <td> <%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %>  </td>
              <% end %>
            <%end%>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<header>
  <div>
    <div class = section-title><%= @issue.Title %></div>
    <div class = section-subtitle>Issue #<%= @issue.id%> <%= link_to @issue.Status , issues_url(status: @issue.Status), class:"btn-link" %></div>
  </div>

  <div>
    <p><strong> <%= User.find(@issue.user_id).name %> </strong> created an issue <small><font color="gray"><%= time_ago_in_words(@issue.created_at) + " ago" %></font></small></p>
    <p><%= @issue.Description %></p>
  </div>
</header>


<div class = "contenedor">
  <div class = "columna">
      <div class="col-md-8">
        <h2>Comentarios (<%= @issue.comments.count %>)</h2>

        <% @issue.comments.each do |comment| %>
          <div class="comments">

            <p class="comenter">
              <%= User.find(comment.user_id).name %>
            </p>

            <p class="coment">
              <%= comment.body %>
              </br>
            </p>

            <p> <% if comment.user_id == current_user.id%>
                <%= link_to 'Delete ', [Issue.find(comment.issue_id), comment],
                            method: :delete,
                            data: { confirm: 'Are you sure?' } , class: "destroy" %> .
              <% end %>
              <small><font color="gray"><%= time_ago_in_words(comment.created_at) + " ago" %></font></small></p>
          </div>
          </br>
        <% end %>


        <%= form_with(model: [@issue, @issue.comments.build], local: true) do |form| %>
          <div id = container>
            <div>
              <%= form.text_area :body %>
            </div>
              <br>
            <div id = "CreateComment">
              <%= form.submit :class => 'submit' %>
            </div>
          </div>
        <% end %>

      </div>
  </div>

  <div class = table-description>

    <div class = "columna2">

      <% if current_user.id == @issue.user_id %>
        <div class="issue-toolbar">
          <div class="dropdown">
      <span style="margin-right:5px; background: #8D8DF4; padding:8px; font-weight: bold">
        <% if @issue.Status == "Open" || @issue.Status == "New" %>
          <a class="resolved"> <%= link_to 'Resolve', update_status_url(id: @issue.id, status: "Resolved"), method: :put %> </a>
        <% else %>
          <%= link_to 'Open', update_status_url(id: @issue.id, status: "Open"), method: :put, class:'open'%>
        <% end %>
      </span>
            <button class="show-button dropdown-toggle next-to" type="button" data-toggle="dropdown">Workflow
              <span class="caret"></span></button>
            <ul class="drop-menu">
              <% Issue.status.each do |status| %>
                <% if status != @issue.Status %>
                  <%= content_tag(:li, link_to(status, update_status_url(id: @issue.id, status: status), method: :put)) %>
                <% end %>
              <% end %>
            </ul>

            <button type="button" class="btn btn-light">
              <span class="createi-button">                         <a href="#" data-toggle="modal" data-target="#attachmodal" class="show-button">Attach</a>

              </span>
            </button>

            <button type="button" class="btn btn-light">
              <span class="createi-button">              <a href="/issues/<%= @issue.id %>/edit" class="show-button">Edit</a>
              </span>
            </button>

            <button type="button" class="btn btn-light">
              <%= link_to 'Delete', @issue,  method: :delete, class: 'show-button', data: { confirm: 'Are you sure you want to delete this issue?' } %>
                <span class="createi-button"></span>
            </button>

             <button type="button" class="btn btn-light">
                <%= link_to new_issue_path, class: 'create-button' do %>
                  <span class="createi-button">Create issue</span>
                <% end %>
              </button>
          </div>
        </div>
      <%end%>

    <div class = border>
    <table class="egt">
      <tr>
        <td class = "label-list">Assignee</td>
        <% if !@issue.assignee_id.nil? %>
          <td class = "link-list"><%= link_to User.find(request.query_parameters[:id]=@issue.assignee_id).name, issues_url(assignee_id: @issue.assignee_id), class:"btn-link" %><td>
        <% else %>
          <td>-</td>
        <% end %>
      </tr>
      <tr>
        <td class = "label-list">Type</td>
        <td class = "link-list"><%= link_to @issue.Type , issues_url(type: @issue.Type), class:"btn-link" %></td>
      </tr>
      <tr>
        <td class = "label-list">Priority</td>
        <td class = "link-list"><%= link_to @issue.Priority , issues_url(priority: @issue.Priority), class:"btn-link" %></td>
      </tr>
      <tr>
        <td class = "label-list">Status</td>
        <td class = "link-list"><%= link_to @issue.Status , issues_url(status: @issue.Status), class:"btn-link" %></td>
      </tr>
      <tr>
        <td  class = "label-list">Votes</td>
        <td class = link-list> <%= @issue.votes.size %>
          <% if !Vote.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
            <%= link_to 'Vote for this issue', vot_path(id: @issue.id), method: :post, class:"btn-link" %>
          <% else %>
            <%= link_to 'Remove vote', vot_path(id: @issue.id), method: :post, class:"btn-link" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td  class = "label-list">Watchers</td>
        <td class = link-list><%= @issue.Watchers %>
          <% if !Watcher.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
            <%= link_to 'Watch', watch_url(id: @issue.id, index: "id"), method: :post, class:"btn-link" %>
          <%else %>
            <%= link_to 'Unwatch', watch_url(id: @issue.id, index: "id"), method: :post, class:"btn-link" %>
          <% end %>
        </td>
      </tr>
    </table>
    </div>
  </div>
  </div>
</div>
</div>
    </div>


<hr>
      <%= link_to 'Back', issues_path %>