config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  resources :users
  resources :issues
  resources :issues do
    resources :comments
  end
  get '/users/current_user' => "users#the_current_user", as: :current_user
  get  'static_pages/home'
  get  'static_pages/help'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  


  #Routes for vote
  post '/issues/:id/vote' => "issues#vote", as: :vot
  post '/issues/:id/watcher/:index' => "issues#watcher", as: :watch
  put '/issues/:id/status' => "issues#update_status", as: :update_status

  put '/issues' => 'application#set_current_user', as: :log



 

end

app/models/watcher.rb
class Watcher < ApplicationRecord
end

app/controllers/watchers_controller.rb
class WatchersController < ApplicationController
  before_action :set_watcher, only: [:show, :edit, :update, :destroy]

  # GET /watchers
  # GET /watchers.json
  def index
    @watchers = Watcher.all
  end

  # GET /watchers/1
  # GET /watchers/1.json
  def show
  end

  # GET /watchers/new
  def new
    @watcher = Watcher.new
  end

  # GET /watchers/1/edit
  def edit
  end

  # POST /watchers
  # POST /watchers.json
  def create
    @watcher = Watcher.new(watcher_params)

    respond_to do |format|
      if @watcher.save
        format.html { redirect_to @watcher, notice: 'Watcher was successfully created.' }
        format.json { render :show, status: :created, location: @watcher }
      else
        format.html { render :new }
        format.json { render json: @watcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchers/1
  # PATCH/PUT /watchers/1.json
  def update
    respond_to do |format|
      if @watcher.update(watcher_params)
        format.html { redirect_to @watcher, notice: 'Watcher was successfully updated.' }
        format.json { render :show, status: :ok, location: @watcher }
      else
        format.html { render :edit }
        format.json { render json: @watcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchers/1
  # DELETE /watchers/1.json
  def destroy
    @watcher.destroy
    respond_to do |format|
      format.html { redirect_to watchers_url, notice: 'Watcher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watcher
      @watcher = Watcher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watcher_params
      params.require(:watcher).permit(:user_id, :issue_id)
    end
end

app/helpers/watchers_helper.rb
module WatchersHelper
end

app/views/watchers/_form.html.erb
<%= form_with(model: watcher, local: true) do |form| %>
  <% if watcher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watcher.errors.count, "error") %> prohibited this watcher from being saved:</h2>

      <ul>
        <% watcher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :issue_id %>
    <%= form.number_field :issue_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/watchers/edit.html.erb
<h1>Editing Watcher</h1>

<%= render 'form', watcher: @watcher %>

<%= link_to 'Show', @watcher %> |
<%= link_to 'Back', watchers_path %>

app/views/watchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Watchers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @watchers.each do |watcher| %>
      <tr>
        <td><%= watcher.user_id %></td>
        <td><%= watcher.issue_id %></td>
        <td><%= link_to 'Show', watcher %></td>
        <td><%= link_to 'Edit', edit_watcher_path(watcher) %></td>
        <td><%= link_to 'Destroy', watcher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watcher', new_watcher_path %>

app/views/watchers/new.html.erb
<h1>New Watcher</h1>

<%= render 'form', watcher: @watcher %>

<%= link_to 'Back', watchers_path %>

app/views/watchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @watcher.user_id %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @watcher.issue_id %>
</p>

<%= link_to 'Edit', edit_watcher_path(@watcher) %> |
<%= link_to 'Back', watchers_path %>